/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

CREATE TABLE `HR_SOURCE_PART_PUB_ORGAN` (
    `_id`  STRING NOT NULL,
    `type` STRING NOT NULL,
    `body` ROW<
        `oid` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL,`value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL,
        `goid` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `coid` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `name` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `shortname` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `status` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `grade` ROW<`text` ARRAY<BIGINT> NOT NULL,`value` ARRAY<BIGINT> NOT NULL> NOT NULL,
        `type` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `typeext` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `biztype` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `crossorgan` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `ocode` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `mrut` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `oper` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `note` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `temorganname` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `organemp` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `startdate` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `projecttype` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `projectmantype` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `projectscale` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `orggrade` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `entclass` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `bizdomain` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `territorypro` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `carea` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `orgprovince` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `organgrade` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `state` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `rown` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `roid` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `qygrade` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `reserve1` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `reserve2` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `bissnes_type` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `projectstatus` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `pay_oid` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `pay_own` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `postal_address` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `is_independent` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `reserve3` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `combinedform` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `enterprise_category` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `approvaltime` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `declareorg` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `declaretime` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `establish_reason` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `establish_reason_other` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `establist_mode` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `contribution_mode` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `contribution_arrange` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `step_paid` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `main_business_area` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `main_business_area_other` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `function_position` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `business_model` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `business_model_other` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `value_contribution` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `value_contribution_other` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `englishname` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `englishshortname` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `waozyywqy` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `waodlkztzyw` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `mdm_code` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,
        `mdm_view_flag` ROW<`text` ARRAY<STRING> NOT NULL,`value` ARRAY<STRING> NOT NULL> NOT NULL,

        `organ_relation` ARRAY<ROW<`o2bid` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `biztype` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `oid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `poid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `gpoid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `goid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `coid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `orule` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `sno` ROW<`text` ARRAY<BIGINT> NOT NULL, `value` ARRAY<BIGINT> NOT NULL>, `type` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `mrut` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `oper` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `note` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `startdate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `typeext` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `grule` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `state` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `global_sno` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bizattr1` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bizattr2` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bizattr3` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bizattr4` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL>>,
        `organ_borginfo` ARRAY<ROW<`id` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `borgid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `registercode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `operatingperiod` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `shareholdings` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `registeraddress` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL>>,
        `borg_jgxx_certificate` ARRAY<ROW<`id` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `borgid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgcode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `certtype` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `certname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `certificate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `downdate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `downuser` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `certstatus` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `serialnumber` ROW<`text` ARRAY<DECIMAL(38, 0)>, `value` ARRAY<DECIMAL(38, 0)>>, `remark` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjcdocumentnumber` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjcfbsj` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjccurrent` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `attachment` ARRAY<ROW<`ID` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILENAME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILESIZE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILETYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `TYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADTIME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADER` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL>>>>,
        `borg_jgxx_dot` ARRAY<ROW<`id` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `borgid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borglevel` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `dotname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `dotcode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `pzrq` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `remark` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `certificate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgcode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `subsidiaryunit` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `attachment` ARRAY<ROW<`ID` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILENAME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILESIZE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILETYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `TYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADTIME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADER` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL>>>>,
        `borg_jgxx_patent` ARRAY<ROW<`id` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `borgid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borglevel` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `patentee` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `patenttyp` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `patentname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `patentnum` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `accredityear` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `expirydate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `accreditorg` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `remark` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `credentials` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgcode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `attachment` ARRAY<ROW<`ID` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILENAME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILESIZE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILETYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `TYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADTIME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADER` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL>>>>,
        `borg_jgxx_qualification` ARRAY<ROW<`id` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `borgid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `qualname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `quallevel` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `certificateno` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `issueunit` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `issuedate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `expirydate` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `supecompunit` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `remark` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgcode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borglevel` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `credentials` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjqzzlb` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `attachment` ARRAY<ROW<`ID` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILENAME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILESIZE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILETYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `TYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADTIME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADER` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL>>>>,
        `borg_jgxx_shareholder` ARRAY<ROW<`id` ROW<`text` ARRAY<STRING NOT NULL> NOT NULL, `value` ARRAY<STRING NOT NULL> NOT NULL> NOT NULL, `borgid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `shartype` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `sharid` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `sharname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `credentials` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `contributivemanner` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `contributivemoney` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `shareholding` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `sharrepresentative` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `duty` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `remark` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgcode` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `borgname` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `sharstructure` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `shareholdingmanner` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `serialnumber` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `shareholdingratio` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `nature` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `carea` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjssjje` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjsrjje` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `bjsczqx` ROW<`text` ARRAY<STRING> NOT NULL, `value` ARRAY<STRING> NOT NULL> NOT NULL, `attachment` ARRAY<ROW<`ID` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILENAME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILESIZE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `FILETYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `TYPE` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADTIME` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL, `UPLOADER` ROW<`TEXT` ARRAY<STRING> NOT NULL, `VALUE` ARRAY<STRING> NOT NULL> NOT NULL>>>>
    >,
    lastUpdate TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (_id) NOT ENFORCED
)
WITH (
    'connector' = 'mongodb',
    'uri' = 'mongodb://root:mongodb@mongodb-cluster-0.mongodb-cluster-headless.mongodb.svc.cluster.local:27017,mongodb-cluster-1.mongodb-cluster-headless.mongodb.svc.cluster.local:27017,mongodb-cluster-2.mongodb-cluster-headless.mongodb.svc.cluster.local:27017/admin?replicaSet=rs0',
    'database' = 'hr',
    'collection' = 'document_integration'
);

insert into HR_SOURCE_PART_PUB_ORGAN
SELECT
    cast( concat('org-',org.OID_KEY) as STRING) oid,
    CAST('organization' AS STRING) type,
    ROW(
        OID,
        GOID,
        COID,
        NAME,
        SHORTNAME,
        STATUS,
        GRADE,
        TYPE,
        TYPEEXT,
        BIZTYPE,
        CROSSORGAN,
        OCODE,
        MRUT,
        OPER,
        NOTE,
        TEMORGANNAME,
        ORGANEMP,
        STARTDATE,
        PROJECTTYPE,
        PROJECTMANTYPE,
        PROJECTSCALE,
        ORGGRADE,
        ENTCLASS,
        BIZDOMAIN,
        TERRITORYPRO,
        CAREA,
        ORGPROVINCE,
        ORGANGRADE,
        STATE,
        ROWN,
        ROID,
        QYGRADE,
        RESERVE1,
        RESERVE2,
        BISSNES_TYPE,
        PROJECTSTATUS,
        PAY_OID,
        PAY_OWN,
        POSTAL_ADDRESS,
        IS_INDEPENDENT,
        RESERVE3,
        COMBINEDFORM,
        ENTERPRISE_CATEGORY,
        APPROVALTIME,
        DECLAREORG,
        DECLARETIME,
        ESTABLISH_REASON,
        ESTABLISH_REASON_OTHER,
        ESTABLIST_MODE,
        CONTRIBUTION_MODE,
        CONTRIBUTION_ARRANGE,
        STEP_PAID,
        MAIN_BUSINESS_AREA,
        MAIN_BUSINESS_AREA_OTHER,
        FUNCTION_POSITION,
        BUSINESS_MODEL,
        BUSINESS_MODEL_OTHER,
        VALUE_CONTRIBUTION,
        VALUE_CONTRIBUTION_OTHER,
        ENGLISHNAME,
        ENGLISHSHORTNAME,
        WAOZYYWQY,
        WAODLKZTZYW,
        MDM_CODE,
        MDM_VIEW_FLAG,
        biz_data,
        base_fdc_info,
        certificate_info,
        dot_info,
        patent_info,
        qualification_info,
        sharehoiler_info
    ) body,
    MaxTimestamp(ARRAY[
        org.TS,
        biz.TS,
        V1202_HR_SOURCE_PART_BASEINFO.TS,
        V1202_HR_SOURCE_PART_CERTIFICATE.TS,
        V1202_HR_SOURCE_PART_DOT.TS,
        V1202_HR_SOURCE_PART_PATENT.TS,
        V1202_HR_SOURCE_PART_QUALIFICATION.TS,
        V1202_HR_SOURCE_PART_SHAREHOLDER.TS
    ]) TS
FROM
    V1202_HR_SOURCE_PART_ORG org
    INNER JOIN V1202_HR_SOURCE_PART_BIZ biz ON org.OID_KEY = biz.oid_key
    LEFT JOIN V1202_HR_SOURCE_PART_BASEINFO ON org.OID_KEY = V1202_HR_SOURCE_PART_BASEINFO.OID_KEY
    LEFT JOIN V1202_HR_SOURCE_PART_CERTIFICATE ON org.OID_KEY = V1202_HR_SOURCE_PART_CERTIFICATE.OID_KEY
    LEFT JOIN V1202_HR_SOURCE_PART_DOT ON org.OID_KEY = V1202_HR_SOURCE_PART_DOT.OID_KEY
    LEFT JOIN V1202_HR_SOURCE_PART_PATENT ON org.OID_KEY = V1202_HR_SOURCE_PART_PATENT.OID_KEY
    LEFT JOIN V1202_HR_SOURCE_PART_QUALIFICATION ON org.OID_KEY = V1202_HR_SOURCE_PART_QUALIFICATION.OID_KEY
    LEFT JOIN V1202_HR_SOURCE_PART_SHAREHOLDER ON org.OID_KEY = V1202_HR_SOURCE_PART_SHAREHOLDER.OID_KEY;





