/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

EXECUTE STATEMENT SET
BEGIN

INSERT INTO PRAOP_HR_EMP_BASICINFO SELECT `EMPCODE`,`NAME`,`NAMESPELL`,`ENNAME`,`NAMEUSED`,`CERTTYPE`,`CERTNO`,`SEX`,`AGE`,`BIRTHDAY`,`BIRTHPLACE`,`RESPLACE`,`RESNATURE`,`NATIONNALITY`,`NATION`,`NATIVEPLACE`,`MARRY`,`WORKTIME`,`SOCIANO`,`PHONE`,`HOMEADDRESS`,`EMAIL`,`POSTALCODE`,`OPTOR`,`OPTTIME`,`OPTORG`,`BESTEDU`,`BESTPROPOST`,`POSTIONS`,`POLITICSFACES`,`WORKPROF`,`BESTDEGREE`,TRY_CAST(`WORKAGE` AS DECIMAL(32, 2)),TRY_CAST(`ENPAGE` AS DECIMAL(32, 2)),TRY_CAST(`UNITACCAGE` AS DECIMAL(32, 2)),TRY_CAST(`GROUPAGE` AS DECIMAL(32, 2)),TRY_CAST(`GROUPACCAGE` AS DECIMAL(32, 2)),`CONTRACTUNIT`,`PHOTO`,`MAINPROFCOTEGORY`,`RECRUITMENT`,`DEPOSITUNIT`,`RETIREMENTDATE`,`POSITIONGRADE`,`RETIREMENTORG`,`RETIREMENTPOSITION`,`EMPIDENTITY`,`STATE`,`STUDYPROF`,`SOCIALTYPE1`,`SOCIALCODE1`,`SOCIALTYPE2`,`SOCIALCODE2`,`ANNUITYNO`,`HOUSINGFUND`,`NOTE`,`TECHPROF`,`EMPID`,`LANDLINE_TELEPHONE_NUMBER`,`FAX`,`ROOM_NUMBER`,`GLOBALROAMING`,`PERSONNELCATEGORY`,`HIERARCHY`,`CTRANK`,`SHJJOBNUMBER`,`SHJEMPTYPE`,`SHJTALENTLEVEL`,`SHJDUTYSTATION`,`SHJ_ZYTXRC`,`SHJ_WDYW`,`SHJ_JWRY`,`SHJ_PQZ`,`SHJ_RCGX`,`SHJ_ISPRO` FROM CDC_HR_EMP_BASICINFO;
INSERT INTO PRAOP_HR_EMP_PROFTECHPOSITIONQUA SELECT `PROFQUAID`,`EMPID`,`PROF`,`PROFTECHQUA`,`GAINWAY`,`GAINQUANO`,`GAINQUATIME`,`APPPROFPOST`,`RANK`,`APPOINTNO`,`APPOINTBEGINTIME`,`APPOINTENDTIME`,`APPOINTSTATUS`,`APPORG`,`CERTNO`,`CERTORG`,`CERTORGPHONE`,`OPTOR`,`OPTTIME`,`OPTORG`,`STATUS`,`NOTE`,`EXCEPCIR`,`EXCEPTIME`,`APPOINTWAY` FROM CDC_HR_EMP_PROFTECHPOSITIONQUA;
INSERT INTO PRAOP_HR_EMP_QUACERTINFO SELECT `QUCERTINFOID`,`EMPID`,`CERTTYPE`,`CERTNAME`,`CERTNO`,`CERTNOZ`,`QUACERTNO`,`REGISNO`,`MANAGERNO`,`CERTORG`,`CERTDATE`,`CERTSTATUS`,`CERTGAINWAY`,`PERIODYEAR`,`MAINPROF`,`AUXILIARYPROF`,`EMPLOYORG`,`SEALREGISNO`,`REGISORG`,`PERIODTYPE`,`REGISBEGINDATE`,`REGISENDDATE`,`ISNOCONTINUEEDU`,`CONTINUEEDUHOURS`,`INSPECTIONDATE`,`INSPECTIONORG`,`INSPECTIONRESULT`,`ENTERPRISENAME`,`POSITION`,`OPTOR`,`OPTTIME`,`OPTORG`,`STATUS`,`NOTE`,`DEPOSITPLACE`,`CERTLV`,`BSTATUS`,`BDATES`,`THREEPROF`,`MAINPROF0`,`MAINPROF1`,`MAINPROF2`,`MAINPROF3`,`MAINPROF4`,`MAINPROF5`,`MAINPROF6`,`MAINPROF7`,`MAINPROF8`,`REGISENDDATE1`,`REGISENDDATE2`,`REGISENDDATE3`,`REGISENDDATE4`,`REGISENDDATE5`,`REGISENDDATE6`,`REGISENDDATE7`,`REGISENDDATE8`,`PRONAME`,`PROQUAGRADE`,`QUANAME_HY`,`QUAGRADE_HY`,`REGISENDDATE_REG`,`REGISENDDATE_GW`,`EMPLOYORG_REG`,`EMPLOYORG_GW`,'' as `PERFORMANCE`,'' as `SOCIAL_UNIT_NAME`,'' as `BACKGROUND` FROM CDC_HR_EMP_QUACERTINFO;
INSERT INTO PRAOP_HR_WORK_EMPPOSITION SELECT `WEPID`,`EMPID`,`OID`,`PCODE`,`ENO`,`EMPSORT`,`EMPSTATUS`,`SUBRELATION`,`ENTRYTIME`,`LEAVETIME`,`FORMALTIME`,`LABCONTRACTSTATUS`,`FORMALSTATUS`,`ISPAYOFF`,`NOTE`,`OPTOR`,`OPTTIME`,`OPTORG`,`ISFULLTIME`,`SOURCE`,`RECRUITMENT`,`DEPOSITUNIT`,`MOVESTIME`,`MOVEETIME`,`QUITREASON`,`STATE`,`ISSHOW`,'' as `ISSOLVE` FROM CDC_HR_WORK_EMPPOSITION;
INSERT INTO PRAOP_HR_WORK_POSTWORKINFO SELECT `WPWID`,`EMPID`,`OFFICEDEPID`,`ORULE`,`CORPRULE`,`OFFICETYPE`,`POSTTYPE`,`POST`,`STARTTIME`,`ENDTIME`,`STATUS`,TRY_CAST(`SNO` AS DECIMAL(32, 2)),`OPTOR`,`OPTTIME`,`OPTORG`,`NOTE`,`WORKPROF`,`STATE`,`WEPID`,`ISSHOW`,`AREA`,`COUNTRY`,`BUSINESSAREA`,`DURATION`,`ISRESUME`,`ISPAYOFF`,`WORKING_COID`,`WORKING_COID_NAME`,`WORKING_POID`,`WORKING_POID_NAME`,`OFFICEDEPNAME`,`POSITIONID`,`POSITIONNAME`,`CERTIFIER`,`POSTCATEGORY`,`POSTGRADATION`,`BUSINESS_AREA_OF_PROJECT`,`ISINGROUP`,`WORKING_COID_SHORTNAME`,`APPOINTNO`,`REMOVALNO`,`SEQUNORM`,`POSITIONGRADENORM`,`POSITIONNORM`,TRY_CAST(`POST_SNO` AS DECIMAL(32, 2)),`FRZL` FROM CDC_HR_WORK_POSTWORKINFO;

END;