/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


CREATE VIEW `V1202_HR_SOURCE_PART_ATTACH`
AS SELECT `BIZID`, `TABLE_NAME`, `KeySet`(COLLECT(ROW(ROW(ARRAY[`ATTACHID`], ARRAY[`ATTACHID`]), ROW(ARRAY[`SOURCEFILE`], ARRAY[`SOURCEFILE`]), ROW(ARRAY[`FILELENGTH`], ARRAY[`FILELENGTH`]), ROW(ARRAY[`FILETYPE`], ARRAY[`FILETYPE`]), ROW(ARRAY[`COL_NAME`], ARRAY[`COL_NAME`]), ROW(ARRAY[`MRUT`], ARRAY[`MRUT`]), ROW(ARRAY[`OPER_NAME`], ARRAY[`OPER_NAME`])))) AS `ATTACHMENT`
   FROM (WITH `FILE_TEMP` AS (SELECT `A`.`ATTACHID`, `A`.`FILELENGTH`, `A`.`MRUT`, `A`.`TARGETPATH`, `A`.`TARGETFILE`, `A`.`SOURCEFILE`, `B`.`EIID`, `B`.`EID`, `B`.`BIZID`, `C`.`NAME` AS `OPER_NAME`
                              FROM `V1202_WAF_APP_ATTACH` AS `A`,
                                   `V1202_WAF_APP_ATTACHREF` AS `B`,
                                   `V1202_WAF_AC_USER` AS `C`
                              WHERE `A`.`ATTACHID` = `B`.`ATTACHID` AND `A`.`OPER` = `C`.`USERID` AND (`B`.`EID` IN ('64762cb4ce8c4ffcad407b2fdc844212', 'c571b469ef82415d83cac3a6d09e14cc', 'fd4809a781044eb3882863831b1a04bc', '197c9e9a7429437b9b5b2fd94fbaa3cc', '90754ce2dd7d4d57a395deddc0b8a68e', '2ff3d066b3b1445f8a08a8bc365b16c8', '2ff3d066b3b1445f8a08a8bc365b16c8', 'c838e7d926d1444b9640e599af77da6d', '9879df2145584b61b145db03dc8f6151', '8efc12445db2409e8cb23c7c6d81c31e') OR `B`.`EID` = 'e1e6afc5ec094abb855e4d8b8382c385' AND `A`.`TARGETPATH` = 'hr/photo')), `ENTITY_TEMP` AS (SELECT `A`.`EID`, `B`.`EIID`, `A`.`CODE` AS `TABLE_NAME`, `B`.`CODE` AS `COL_NAME`, `A`.`PRIMARYKEY`
        FROM `V1202_WAF_CORE_ENTITY` AS `A`,
           `V1202_WAF_CORE_ENTITYITEM` AS `B`
        WHERE `A`.`EID` = `B`.`EID`), `TEMP` AS (SELECT `A`.`ATTACHID`, `A`.`FILELENGTH`, `A`.`SOURCEFILE`, `B`.`TABLE_NAME`, `B`.`COL_NAME`, `B`.`PRIMARYKEY` AS `REFER_FILED`, `A`.`BIZID`, `A`.`MRUT`, `A`.`OPER_NAME`, CASE WHEN `B`.`TABLE_NAME` = 'borg_jgxx_certificate' THEN 'certificate' WHEN `B`.`TABLE_NAME` = 'borg_jgxx_dot' THEN 'certificate' WHEN `B`.`TABLE_NAME` = 'borg_jgxx_patent' THEN 'certificate' WHEN `B`.`TABLE_NAME` = 'borg_jgxx_qualification' THEN 'certificate' WHEN `B`.`TABLE_NAME` = 'hr_emp_proftechpositionqua' THEN 'proftechaccessory' WHEN `B`.`TABLE_NAME` = 'hr_emp_quacertinfo' THEN 'quacertaccessory' WHEN `B`.`TABLE_NAME` = 'hr_emp_validpassport' THEN 'validpassportaccessory' WHEN `B`.`TABLE_NAME` = 'hr_emp_basicinfo' THEN 'photo' WHEN `B`.`TABLE_NAME` = 'hr_emp_academicdegreecert' THEN `B`.`COL_NAME` ELSE '' END AS `FILETYPE`
                                               FROM `FILE_TEMP` AS `A`,
                                                    `ENTITY_TEMP` AS `B`
                                               WHERE `A`.`EID` = `B`.`EID` AND `A`.`EIID` = `B`.`EIID`) (SELECT *
                                                                                                      FROM `TEMP`)) GROUP BY `TABLE_NAME`, `BIZID`;


CREATE VIEW `V1202_HR_SOURCE_PART_ORG`
AS SELECT `OID` AS `OID_KEY`, `TS`, ROW(ARRAY[`OID`], ARRAY[`OID`]) AS `OID`, ROW(ARRAY[`GOID`], ARRAY[`GOID`]) AS `GOID`, ROW(ARRAY[`COID`], ARRAY[`COID`]) AS `COID`, ROW(ARRAY[`NAME`], ARRAY[`NAME`]) AS `NAME`, ROW(ARRAY[`SHORTNAME`], ARRAY[`SHORTNAME`]) AS `SHORTNAME`, ROW(ARRAY[`STATUS`], ARRAY[`STATUS`]) AS `STATUS`, ROW(ARRAY[`GRADE`], ARRAY[`GRADE`]) AS `GRADE`, ROW(ARRAY[`TYPE`], ARRAY[`TYPE`]) AS `TYPE`, ROW(ARRAY[`TYPEEXT`], ARRAY[`TYPEEXT`]) AS `TYPEEXT`, ROW(ARRAY[`BIZTYPE`], ARRAY[`BIZTYPE`]) AS `BIZTYPE`, ROW(ARRAY[`CROSSORGAN`], ARRAY[`CROSSORGAN`]) AS `CROSSORGAN`, ROW(ARRAY[`OCODE`], ARRAY[`OCODE`]) AS `OCODE`, ROW(ARRAY[`MRUT`], ARRAY[`MRUT`]) AS `MRUT`, ROW(ARRAY[`OPER`], ARRAY[`OPER`]) AS `OPER`, ROW(ARRAY[`NOTE`], ARRAY[`NOTE`]) AS `NOTE`, ROW(ARRAY[`TEMORGANNAME`], ARRAY[`TEMORGANNAME`]) AS `TEMORGANNAME`, ROW(ARRAY[`ORGANEMP`], ARRAY[`ORGANEMP`]) AS `ORGANEMP`, ROW(ARRAY[`STARTDATE`], ARRAY[`STARTDATE`]) AS `STARTDATE`, ROW(ARRAY[`PROJECTTYPE`], ARRAY[`PROJECTTYPE`]) AS `PROJECTTYPE`, ROW(ARRAY[`PROJECTMANTYPE`], ARRAY[`PROJECTMANTYPE`]) AS `PROJECTMANTYPE`, ROW(ARRAY[`PROJECTSCALE`], ARRAY[`PROJECTSCALE`]) AS `PROJECTSCALE`, ROW(ARRAY[`ORGGRADE`], ARRAY[`ORGGRADE`]) AS `ORGGRADE`, ROW(ARRAY[`ENTCLASS`], ARRAY[`ENTCLASS`]) AS `ENTCLASS`, ROW(ARRAY[`BIZDOMAIN`], ARRAY[`BIZDOMAIN`]) AS `BIZDOMAIN`, ROW(ARRAY[`TERRITORYPRO`], ARRAY[`TERRITORYPRO`]) AS `TERRITORYPRO`, ROW(ARRAY[`CAREA`], ARRAY[`CAREA`]) AS `CAREA`, ROW(ARRAY[`ORGPROVINCE`], ARRAY[`ORGPROVINCE`]) AS `ORGPROVINCE`, ROW(ARRAY[`ORGANGRADE`], ARRAY[`ORGANGRADE`]) AS `ORGANGRADE`, ROW(ARRAY[`STATE`], ARRAY[`STATE`]) AS `STATE`, ROW(ARRAY[`ROWN`], ARRAY[`ROWN`]) AS `ROWN`, ROW(ARRAY[`ROID`], ARRAY[`ROID`]) AS `ROID`, ROW(ARRAY[`QYGRADE`], ARRAY[`QYGRADE`]) AS `QYGRADE`, ROW(ARRAY[`RESERVE1`], ARRAY[`RESERVE1`]) AS `RESERVE1`, ROW(ARRAY[`RESERVE2`], ARRAY[`RESERVE2`]) AS `RESERVE2`, ROW(ARRAY[`BISSNES_TYPE`], ARRAY[`BISSNES_TYPE`]) AS `BISSNES_TYPE`, ROW(ARRAY[`PROJECTSTATUS`], ARRAY[`PROJECTSTATUS`]) AS `PROJECTSTATUS`, ROW(ARRAY[`PAY_OID`], ARRAY[`PAY_OID`]) AS `PAY_OID`, ROW(ARRAY[`PAY_OWN`], ARRAY[`PAY_OWN`]) AS `PAY_OWN`, ROW(ARRAY[`POSTAL_ADDRESS`], ARRAY[`POSTAL_ADDRESS`]) AS `POSTAL_ADDRESS`, ROW(ARRAY[`IS_INDEPENDENT`], ARRAY[`IS_INDEPENDENT`]) AS `IS_INDEPENDENT`, ROW(ARRAY[`RESERVE3`], ARRAY[`RESERVE3`]) AS `RESERVE3`, ROW(ARRAY[`COMBINEDFORM`], ARRAY[`COMBINEDFORM`]) AS `COMBINEDFORM`, ROW(ARRAY[`ENTERPRISE_CATEGORY`], ARRAY[`ENTERPRISE_CATEGORY`]) AS `ENTERPRISE_CATEGORY`, ROW(ARRAY[`APPROVALTIME`], ARRAY[`APPROVALTIME`]) AS `APPROVALTIME`, ROW(ARRAY[`DECLAREORG`], ARRAY[`DECLAREORG`]) AS `DECLAREORG`, ROW(ARRAY[`DECLARETIME`], ARRAY[`DECLARETIME`]) AS `DECLARETIME`, ROW(ARRAY[`ESTABLISH_REASON`], ARRAY[`ESTABLISH_REASON`]) AS `ESTABLISH_REASON`, ROW(ARRAY[`ESTABLISH_REASON_OTHER`], ARRAY[`ESTABLISH_REASON_OTHER`]) AS `ESTABLISH_REASON_OTHER`, ROW(ARRAY[`ESTABLIST_MODE`], ARRAY[`ESTABLIST_MODE`]) AS `ESTABLIST_MODE`, ROW(ARRAY[`CONTRIBUTION_MODE`], ARRAY[`CONTRIBUTION_MODE`]) AS `CONTRIBUTION_MODE`, ROW(ARRAY[`CONTRIBUTION_ARRANGE`], ARRAY[`CONTRIBUTION_ARRANGE`]) AS `CONTRIBUTION_ARRANGE`, ROW(ARRAY[`STEP_PAID`], ARRAY[`STEP_PAID`]) AS `STEP_PAID`, ROW(ARRAY[`MAIN_BUSINESS_AREA`], ARRAY[`MAIN_BUSINESS_AREA`]) AS `MAIN_BUSINESS_AREA`, ROW(ARRAY[`MAIN_BUSINESS_AREA_OTHER`], ARRAY[`MAIN_BUSINESS_AREA_OTHER`]) AS `MAIN_BUSINESS_AREA_OTHER`, ROW(ARRAY[`FUNCTION_POSITION`], ARRAY[`FUNCTION_POSITION`]) AS `FUNCTION_POSITION`, ROW(ARRAY[`BUSINESS_MODEL`], ARRAY[`BUSINESS_MODEL`]) AS `BUSINESS_MODEL`, ROW(ARRAY[`BUSINESS_MODEL_OTHER`], ARRAY[`BUSINESS_MODEL_OTHER`]) AS `BUSINESS_MODEL_OTHER`, ROW(ARRAY[`VALUE_CONTRIBUTION`], ARRAY[`VALUE_CONTRIBUTION`]) AS `VALUE_CONTRIBUTION`, ROW(ARRAY[`VALUE_CONTRIBUTION_OTHER`], ARRAY[`VALUE_CONTRIBUTION_OTHER`]) AS `VALUE_CONTRIBUTION_OTHER`, ROW(ARRAY[`ENGLISHNAME`], ARRAY[`ENGLISHNAME`]) AS `ENGLISHNAME`, ROW(ARRAY[`ENGLISHSHORTNAME`], ARRAY[`ENGLISHSHORTNAME`]) AS `ENGLISHSHORTNAME`, ROW(ARRAY[`WAOZYYWQY`], ARRAY[`WAOZYYWQY`]) AS `WAOZYYWQY`, ROW(ARRAY[`WAODLKZTZYW`], ARRAY[`WAODLKZTZYW`]) AS `WAODLKZTZYW`, ROW(ARRAY[`MDM_CODE`], ARRAY[`MDM_CODE`]) AS `MDM_CODE`, ROW(ARRAY[`MDM_VIEW_FLAG`], ARRAY[`MDM_VIEW_FLAG`]) AS `MDM_VIEW_FLAG`
   FROM `WAF_AC_ORGAN`;



CREATE VIEW `V1202_HR_SOURCE_PART_BIZ`
AS SELECT `oid_key`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`O2BID`, `BIZTYPE`, `OID`, `POID`, `GPOID`, `GOID`, `COID`, `ORULE`, `SNO`, `TYPE`, `MRUT`, `OPER`, `NOTE`, `STARTDATE`, `TYPEEXT`, `GRULE`, `STATE`, `GLOBAL_SNO`, `BIZATTR1`, `BIZATTR2`, `BIZATTR3`, `BIZATTR4`))) AS `biz_data`
   FROM (SELECT `OID` AS `oid_key`, `TS`, ROW(ARRAY[`O2BID`], ARRAY[`O2BID`]) AS `O2BID`, ROW(ARRAY[`BIZTYPE`], ARRAY[`BIZTYPE`]) AS `BIZTYPE`, ROW(ARRAY[`OID`], ARRAY[`OID`]) AS `OID`, ROW(ARRAY[`POID`], ARRAY[`POID`]) AS `POID`, ROW(ARRAY[`GPOID`], ARRAY[`GPOID`]) AS `GPOID`, ROW(ARRAY[`GOID`], ARRAY[`GOID`]) AS `GOID`, ROW(ARRAY[`COID`], ARRAY[`COID`]) AS `COID`, ROW(ARRAY[`ORULE`], ARRAY[`ORULE`]) AS `ORULE`, ROW(ARRAY[`SNO`], ARRAY[`SNO`]) AS `SNO`, ROW(ARRAY[`TYPE`], ARRAY[`TYPE`]) AS `TYPE`, ROW(ARRAY[`MRUT`], ARRAY[`MRUT`]) AS `MRUT`, ROW(ARRAY[`OPER`], ARRAY[`OPER`]) AS `OPER`, ROW(ARRAY[`NOTE`], ARRAY[`NOTE`]) AS `NOTE`, ROW(ARRAY[`STARTDATE`], ARRAY[`STARTDATE`]) AS `STARTDATE`, ROW(ARRAY[`TYPEEXT`], ARRAY[`TYPEEXT`]) AS `TYPEEXT`, ROW(ARRAY[`GRULE`], ARRAY[`GRULE`]) AS `GRULE`, ROW(ARRAY[`STATE`], ARRAY[`STATE`]) AS `STATE`, ROW(ARRAY[`GLOBAL_SNO`], ARRAY[`GLOBAL_SNO`]) AS `GLOBAL_SNO`, ROW(ARRAY[`BIZATTR1`], ARRAY[`BIZATTR1`]) AS `BIZATTR1`, ROW(ARRAY[`BIZATTR2`], ARRAY[`BIZATTR2`]) AS `BIZATTR2`, ROW(ARRAY[`BIZATTR3`], ARRAY[`BIZATTR3`]) AS `BIZATTR3`, ROW(ARRAY[`BIZATTR4`], ARRAY[`BIZATTR4`]) AS `BIZATTR4`
         FROM `WAF_AC_ORGAN2BIZ`
         WHERE `BIZTYPE` = 'base')
   GROUP BY `oid_key`;



CREATE VIEW `V1202_HR_SOURCE_PART_BASEINFO`
AS SELECT `OID_KEY`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `ENTERPRISENAME`, `REGISTERCODE`, `BORGTYPE`, `CORPORATION`, `REGISTERCAPITAL`, `PAIDCAPITAL`, `REGISTERDATE`, `OPERATINGPERIOD`, `DOMICILE`, `ENTERPRISLEVEL`, `SHAREHOLDINGS`, `BUSINESSAREAS`, `EMPLOYEESNUM`, `REGIONALATTRIBUTE`, `REGISTERADDRESS`, `REGISTERORGAN`, `REGISTERSTATUS`, `REMARK`, `ENTERPRISECODE`, `BORGCODE`, `SHORTNAME`, `ENGLISHNAME`, `ENGLISHSHORTNAME`, `EXPIRYDATE`, `ENTERPRISENATURE`, `KONGGGD`, `BINGBDW`, `KONGGOID`, `BINGBOID`, `ISYJ`, `YJSJ`, `CGZT`, `BGRQ`, `PIZDW`, `PIZDWOID`, `ZZXS`, `YJTJ`, `PARENT_CGQK`, `PARENT_CGZT`, `SJYJSJ`, `PHONE`, `LXR`, `SJYJTJ`, `BJBADDMODE`, `BJBPZWH`, `BJBCZSJ`, `BJBISDLKH`, `BJBISSDFA`, `BJBISHGQY`, `BJBLOGO`, `BJBGW`, `BJBYX`, `BJBGSJJ`, `BJBZCZBBZ`, `BJBSSZBBZ`, `OFFICE_LOCATION_PROVINCE`, `OFFICE_LOCATION_CITY`, `JOINT_OFFICE`, `JOINT_OFFICE_UNIT`, `DOC_FILING`, `DOC_FILING_DATE`, `NDRC_FILING`, `NDRC_FILING_DATE`))) AS `base_info`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `REGISTERCODE`, `OPERATINGPERIOD`, `SHAREHOLDINGS`, `REGISTERADDRESS`))) AS `base_fdc_info`
   FROM (SELECT `BORGID` AS `OID_KEY`, `TS`, ROW(ARRAY[`ID`], ARRAY[`ID`]) AS `ID`, ROW(ARRAY[`BORGID`], ARRAY[`BORGID`]) AS `BORGID`, ROW(ARRAY[`ENTERPRISENAME`], ARRAY[`ENTERPRISENAME`]) AS `ENTERPRISENAME`, ROW(ARRAY[`REGISTERCODE`], ARRAY[`REGISTERCODE`]) AS `REGISTERCODE`, ROW(ARRAY[`BORGTYPE`], ARRAY[`BORGTYPE`]) AS `BORGTYPE`, ROW(ARRAY[`CORPORATION`], ARRAY[`CORPORATION`]) AS `CORPORATION`, ROW(ARRAY[`REGISTERCAPITAL`], ARRAY[`REGISTERCAPITAL`]) AS `REGISTERCAPITAL`, ROW(ARRAY[`PAIDCAPITAL`], ARRAY[`PAIDCAPITAL`]) AS `PAIDCAPITAL`, ROW(ARRAY[`REGISTERDATE`], ARRAY[`REGISTERDATE`]) AS `REGISTERDATE`, ROW(ARRAY[`OPERATINGPERIOD`], ARRAY[`OPERATINGPERIOD`]) AS `OPERATINGPERIOD`, ROW(ARRAY[`DOMICILE`], ARRAY[`DOMICILE`]) AS `DOMICILE`, ROW(ARRAY[`ENTERPRISLEVEL`], ARRAY[`ENTERPRISLEVEL`]) AS `ENTERPRISLEVEL`, ROW(ARRAY[`SHAREHOLDINGS`], ARRAY[`SHAREHOLDINGS`]) AS `SHAREHOLDINGS`, ROW(ARRAY[`BUSINESSAREAS`], ARRAY[`BUSINESSAREAS`]) AS `BUSINESSAREAS`, ROW(ARRAY[`EMPLOYEESNUM`], ARRAY[`EMPLOYEESNUM`]) AS `EMPLOYEESNUM`, ROW(ARRAY[`REGIONALATTRIBUTE`], ARRAY[`REGIONALATTRIBUTE`]) AS `REGIONALATTRIBUTE`, ROW(ARRAY[`REGISTERADDRESS`], ARRAY[`REGISTERADDRESS`]) AS `REGISTERADDRESS`, ROW(ARRAY[`REGISTERORGAN`], ARRAY[`REGISTERORGAN`]) AS `REGISTERORGAN`, ROW(ARRAY[`REGISTERSTATUS`], ARRAY[`REGISTERSTATUS`]) AS `REGISTERSTATUS`, ROW(ARRAY[`REMARK`], ARRAY[`REMARK`]) AS `REMARK`, ROW(ARRAY[`ENTERPRISECODE`], ARRAY[`ENTERPRISECODE`]) AS `ENTERPRISECODE`, ROW(ARRAY[`BORGCODE`], ARRAY[`BORGCODE`]) AS `BORGCODE`, ROW(ARRAY[`SHORTNAME`], ARRAY[`SHORTNAME`]) AS `SHORTNAME`, ROW(ARRAY[`ENGLISHNAME`], ARRAY[`ENGLISHNAME`]) AS `ENGLISHNAME`, ROW(ARRAY[`ENGLISHSHORTNAME`], ARRAY[`ENGLISHSHORTNAME`]) AS `ENGLISHSHORTNAME`, ROW(ARRAY[`EXPIRYDATE`], ARRAY[`EXPIRYDATE`]) AS `EXPIRYDATE`, ROW(ARRAY[`ENTERPRISENATURE`], ARRAY[`ENTERPRISENATURE`]) AS `ENTERPRISENATURE`, ROW(ARRAY[`KONGGGD`], ARRAY[`KONGGGD`]) AS `KONGGGD`, ROW(ARRAY[`BINGBDW`], ARRAY[`BINGBDW`]) AS `BINGBDW`, ROW(ARRAY[`KONGGOID`], ARRAY[`KONGGOID`]) AS `KONGGOID`, ROW(ARRAY[`BINGBOID`], ARRAY[`BINGBOID`]) AS `BINGBOID`, ROW(ARRAY[`ISYJ`], ARRAY[`ISYJ`]) AS `ISYJ`, ROW(ARRAY[`YJSJ`], ARRAY[`YJSJ`]) AS `YJSJ`, ROW(ARRAY[`CGZT`], ARRAY[`CGZT`]) AS `CGZT`, ROW(ARRAY[`BGRQ`], ARRAY[`BGRQ`]) AS `BGRQ`, ROW(ARRAY[`PIZDW`], ARRAY[`PIZDW`]) AS `PIZDW`, ROW(ARRAY[`PIZDWOID`], ARRAY[`PIZDWOID`]) AS `PIZDWOID`, ROW(ARRAY[`ZZXS`], ARRAY[`ZZXS`]) AS `ZZXS`, ROW(ARRAY[`YJTJ`], ARRAY[`YJTJ`]) AS `YJTJ`, ROW(ARRAY[`PARENT_CGQK`], ARRAY[`PARENT_CGQK`]) AS `PARENT_CGQK`, ROW(ARRAY[`PARENT_CGZT`], ARRAY[`PARENT_CGZT`]) AS `PARENT_CGZT`, ROW(ARRAY[`SJYJSJ`], ARRAY[`SJYJSJ`]) AS `SJYJSJ`, ROW(ARRAY[`PHONE`], ARRAY[`PHONE`]) AS `PHONE`, ROW(ARRAY[`LXR`], ARRAY[`LXR`]) AS `LXR`, ROW(ARRAY[`SJYJTJ`], ARRAY[`SJYJTJ`]) AS `SJYJTJ`, ROW(ARRAY[`BJBADDMODE`], ARRAY[`BJBADDMODE`]) AS `BJBADDMODE`, ROW(ARRAY[`BJBPZWH`], ARRAY[`BJBPZWH`]) AS `BJBPZWH`, ROW(ARRAY[`BJBCZSJ`], ARRAY[`BJBCZSJ`]) AS `BJBCZSJ`, ROW(ARRAY[`BJBISDLKH`], ARRAY[`BJBISDLKH`]) AS `BJBISDLKH`, ROW(ARRAY[`BJBISSDFA`], ARRAY[`BJBISSDFA`]) AS `BJBISSDFA`, ROW(ARRAY[`BJBISHGQY`], ARRAY[`BJBISHGQY`]) AS `BJBISHGQY`, ROW(ARRAY[`BJBLOGO`], ARRAY[`BJBLOGO`]) AS `BJBLOGO`, ROW(ARRAY[`BJBGW`], ARRAY[`BJBGW`]) AS `BJBGW`, ROW(ARRAY[`BJBYX`], ARRAY[`BJBYX`]) AS `BJBYX`, ROW(ARRAY[`BJBGSJJ`], ARRAY[`BJBGSJJ`]) AS `BJBGSJJ`, ROW(ARRAY[`BJBZCZBBZ`], ARRAY[`BJBZCZBBZ`]) AS `BJBZCZBBZ`, ROW(ARRAY[`BJBSSZBBZ`], ARRAY[`BJBSSZBBZ`]) AS `BJBSSZBBZ`, ROW(ARRAY[`OFFICE_LOCATION_PROVINCE`], ARRAY[`OFFICE_LOCATION_PROVINCE`]) AS `OFFICE_LOCATION_PROVINCE`, ROW(ARRAY[`OFFICE_LOCATION_CITY`], ARRAY[`OFFICE_LOCATION_CITY`]) AS `OFFICE_LOCATION_CITY`, ROW(ARRAY[`JOINT_OFFICE`], ARRAY[`JOINT_OFFICE`]) AS `JOINT_OFFICE`, ROW(ARRAY[`JOINT_OFFICE_UNIT`], ARRAY[`JOINT_OFFICE_UNIT`]) AS `JOINT_OFFICE_UNIT`, ROW(ARRAY[`DOC_FILING`], ARRAY[`DOC_FILING`]) AS `DOC_FILING`, ROW(ARRAY[`DOC_FILING_DATE`], ARRAY[`DOC_FILING_DATE`]) AS `DOC_FILING_DATE`, ROW(ARRAY[`NDRC_FILING`], ARRAY[`NDRC_FILING`]) AS `NDRC_FILING`, ROW(ARRAY[`NDRC_FILING_DATE`], ARRAY[`NDRC_FILING_DATE`]) AS `NDRC_FILING_DATE`
         FROM (SELECT *
               FROM `BORG_JGXX_BASEINFO`
               WHERE `BORGID` IS NOT NULL))
   GROUP BY `OID_KEY`;



CREATE VIEW `V1202_HR_SOURCE_PART_CERTIFICATE`
AS SELECT `OID_KEY`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `BORGCODE`, `BORGNAME`, `CERTTYPE`, `CERTNAME`, `CERTIFICATE`, `DOWNDATE`, `DOWNUSER`, `CERTSTATUS`, `SERIALNUMBER`, `REMARK`, `BJCDOCUMENTNUMBER`, `BJCFBSJ`, `BJCCURRENT`, `ATTACHMENT`))) AS `certificate_info`
   FROM (SELECT `BORGID` AS `OID_KEY`, `TS`, ROW(ARRAY[`ID`], ARRAY[`ID`]) AS `ID`, ROW(ARRAY[`BORGID`], ARRAY[`BORGID`]) AS `BORGID`, ROW(ARRAY[`BORGCODE`], ARRAY[`BORGCODE`]) AS `BORGCODE`, ROW(ARRAY[`BORGNAME`], ARRAY[`BORGNAME`]) AS `BORGNAME`, ROW(ARRAY[`CERTTYPE`], ARRAY[`CERTTYPE`]) AS `CERTTYPE`, ROW(ARRAY[`CERTNAME`], ARRAY[`CERTNAME`]) AS `CERTNAME`, ROW(ARRAY[`CERTIFICATE`], ARRAY[`CERTIFICATE`]) AS `CERTIFICATE`, ROW(ARRAY[`DOWNDATE`], ARRAY[`DOWNDATE`]) AS `DOWNDATE`, ROW(ARRAY[`DOWNUSER`], ARRAY[`DOWNUSER`]) AS `DOWNUSER`, ROW(ARRAY[`CERTSTATUS`], ARRAY[`CERTSTATUS`]) AS `CERTSTATUS`, ROW(ARRAY[`SERIALNUMBER`], ARRAY[`SERIALNUMBER`]) AS `SERIALNUMBER`, ROW(ARRAY[`REMARK`], ARRAY[`REMARK`]) AS `REMARK`, ROW(ARRAY[`BJCDOCUMENTNUMBER`], ARRAY[`BJCDOCUMENTNUMBER`]) AS `BJCDOCUMENTNUMBER`, ROW(ARRAY[`BJCFBSJ`], ARRAY[`BJCFBSJ`]) AS `BJCFBSJ`, ROW(ARRAY[`BJCCURRENT`], ARRAY[`BJCCURRENT`]) AS `BJCCURRENT`, `ATTACHMENT`
         FROM (SELECT *
               FROM `BORG_JGXX_CERTIFICATE`
               WHERE `BORGID` IS NOT NULL) AS `BORG_JGXX_CERTIFICATE`
                  LEFT JOIN (SELECT `BIZID`, `ATTACHMENT`
                             FROM `V1202_HR_SOURCE_PART_ATTACH`
                             WHERE `TABLE_NAME` = 'borg_jgxx_certificate') AS `ATTACH` ON `BORG_JGXX_CERTIFICATE`.`ID` = `ATTACH`.`BIZID`)
   GROUP BY `OID_KEY`;


CREATE VIEW `V1202_HR_SOURCE_PART_DOT`
AS SELECT `OID_KEY`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `BORGNAME`, `BORGLEVEL`, `DOTNAME`, `DOTCODE`, `PZRQ`, `REMARK`, `CERTIFICATE`, `BORGCODE`, `SUBSIDIARYUNIT`, `ATTACHMENT`))) AS `dot_info`
   FROM (SELECT `BORGID` AS `OID_KEY`, `TS`, ROW(ARRAY[`ID`], ARRAY[`ID`]) AS `ID`, ROW(ARRAY[`BORGID`], ARRAY[`BORGID`]) AS `BORGID`, ROW(ARRAY[`BORGNAME`], ARRAY[`BORGNAME`]) AS `BORGNAME`, ROW(ARRAY[`BORGLEVEL`], ARRAY[`BORGLEVEL`]) AS `BORGLEVEL`, ROW(ARRAY[`DOTNAME`], ARRAY[`DOTNAME`]) AS `DOTNAME`, ROW(ARRAY[`DOTCODE`], ARRAY[`DOTCODE`]) AS `DOTCODE`, ROW(ARRAY[`PZRQ`], ARRAY[`PZRQ`]) AS `PZRQ`, ROW(ARRAY[`REMARK`], ARRAY[`REMARK`]) AS `REMARK`, ROW(ARRAY[`CERTIFICATE`], ARRAY[`CERTIFICATE`]) AS `CERTIFICATE`, ROW(ARRAY[`BORGCODE`], ARRAY[`BORGCODE`]) AS `BORGCODE`, ROW(ARRAY[`SUBSIDIARYUNIT`], ARRAY[`SUBSIDIARYUNIT`]) AS `SUBSIDIARYUNIT`, `ATTACHMENT`
         FROM (SELECT *
               FROM `BORG_JGXX_DOT`
               WHERE `BORGID` IS NOT NULL) AS `BORG_JGXX_DOT`
                  LEFT JOIN (SELECT `BIZID`, `ATTACHMENT`
                             FROM `V1202_HR_SOURCE_PART_ATTACH`
                             WHERE `TABLE_NAME` = 'borg_jgxx_dot') AS `ATTACH` ON `BORG_JGXX_DOT`.`ID` = `ATTACH`.`BIZID`)
   GROUP BY `OID_KEY`;


CREATE VIEW `V1202_HR_SOURCE_PART_PATENT`
AS SELECT `OID_KEY`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `BORGNAME`, `BORGLEVEL`, `PATENTEE`, `PATENTTYP`, `PATENTNAME`, `PATENTNUM`, `ACCREDITYEAR`, `EXPIRYDATE`, `ACCREDITORG`, `REMARK`, `CREDENTIALS`, `BORGCODE`, `ATTACHMENT`))) AS `patent_info`
   FROM (SELECT `BORGID` AS `OID_KEY`, `TS`, ROW(ARRAY[`ID`], ARRAY[`ID`]) AS `ID`, ROW(ARRAY[`BORGID`], ARRAY[`BORGID`]) AS `BORGID`, ROW(ARRAY[`BORGNAME`], ARRAY[`BORGNAME`]) AS `BORGNAME`, ROW(ARRAY[`BORGLEVEL`], ARRAY[`BORGLEVEL`]) AS `BORGLEVEL`, ROW(ARRAY[`PATENTEE`], ARRAY[`PATENTEE`]) AS `PATENTEE`, ROW(ARRAY[`PATENTTYP`], ARRAY[`PATENTTYP`]) AS `PATENTTYP`, ROW(ARRAY[`PATENTNAME`], ARRAY[`PATENTNAME`]) AS `PATENTNAME`, ROW(ARRAY[`PATENTNUM`], ARRAY[`PATENTNUM`]) AS `PATENTNUM`, ROW(ARRAY[`ACCREDITYEAR`], ARRAY[`ACCREDITYEAR`]) AS `ACCREDITYEAR`, ROW(ARRAY[`EXPIRYDATE`], ARRAY[`EXPIRYDATE`]) AS `EXPIRYDATE`, ROW(ARRAY[`ACCREDITORG`], ARRAY[`ACCREDITORG`]) AS `ACCREDITORG`, ROW(ARRAY[`REMARK`], ARRAY[`REMARK`]) AS `REMARK`, ROW(ARRAY[`CREDENTIALS`], ARRAY[`CREDENTIALS`]) AS `CREDENTIALS`, ROW(ARRAY[`BORGCODE`], ARRAY[`BORGCODE`]) AS `BORGCODE`, `ATTACHMENT`
         FROM (SELECT *
               FROM `BORG_JGXX_PATENT`
               WHERE `BORGID` IS NOT NULL) AS `BORG_JGXX_PATENT`
                  LEFT JOIN (SELECT `BIZID`, `ATTACHMENT`
                             FROM `V1202_HR_SOURCE_PART_ATTACH`
                             WHERE `TABLE_NAME` = 'borg_jgxx_patent') AS `ATTACH` ON `BORG_JGXX_PATENT`.`ID` = `ATTACH`.`BIZID`)
   GROUP BY `OID_KEY`;


CREATE VIEW `V1202_HR_SOURCE_PART_QUALIFICATION`
AS SELECT `OID_KEY`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `QUALNAME`, `QUALLEVEL`, `CERTIFICATENO`, `ISSUEUNIT`, `ISSUEDATE`, `EXPIRYDATE`, `SUPECOMPUNIT`, `REMARK`, `BORGCODE`, `BORGNAME`, `BORGLEVEL`, `CREDENTIALS`, `BJQZZLB`, `ATTACHMENT`))) AS `qualification_info`
   FROM (SELECT `BORGID` AS `OID_KEY`, `TS`, ROW(ARRAY[`ID`], ARRAY[`ID`]) AS `ID`, ROW(ARRAY[`BORGID`], ARRAY[`BORGID`]) AS `BORGID`, ROW(ARRAY[`QUALNAME`], ARRAY[`QUALNAME`]) AS `QUALNAME`, ROW(ARRAY[`QUALLEVEL`], ARRAY[`QUALLEVEL`]) AS `QUALLEVEL`, ROW(ARRAY[`CERTIFICATENO`], ARRAY[`CERTIFICATENO`]) AS `CERTIFICATENO`, ROW(ARRAY[`ISSUEUNIT`], ARRAY[`ISSUEUNIT`]) AS `ISSUEUNIT`, ROW(ARRAY[`ISSUEDATE`], ARRAY[`ISSUEDATE`]) AS `ISSUEDATE`, ROW(ARRAY[`EXPIRYDATE`], ARRAY[`EXPIRYDATE`]) AS `EXPIRYDATE`, ROW(ARRAY[`SUPECOMPUNIT`], ARRAY[`SUPECOMPUNIT`]) AS `SUPECOMPUNIT`, ROW(ARRAY[`REMARK`], ARRAY[`REMARK`]) AS `REMARK`, ROW(ARRAY[`BORGCODE`], ARRAY[`BORGCODE`]) AS `BORGCODE`, ROW(ARRAY[`BORGNAME`], ARRAY[`BORGNAME`]) AS `BORGNAME`, ROW(ARRAY[`BORGLEVEL`], ARRAY[`BORGLEVEL`]) AS `BORGLEVEL`, ROW(ARRAY[`CREDENTIALS`], ARRAY[`CREDENTIALS`]) AS `CREDENTIALS`, ROW(ARRAY[`BJQZZLB`], ARRAY[`BJQZZLB`]) AS `BJQZZLB`, `ATTACHMENT`
         FROM (SELECT *
               FROM `BORG_JGXX_QUALIFICATION`
               WHERE `BORGID` IS NOT NULL) AS `BORG_JGXX_QUALIFICATION`
                  LEFT JOIN (SELECT `BIZID`, `ATTACHMENT`
                             FROM `V1202_HR_SOURCE_PART_ATTACH`
                             WHERE `TABLE_NAME` = 'borg_jgxx_qualification') AS `ATTACH` ON `BORG_JGXX_QUALIFICATION`.`ID` = `ATTACH`.`BIZID`)
   GROUP BY `OID_KEY`;

CREATE VIEW `V1202_HR_SOURCE_PART_SHAREHOLDER`
AS SELECT `OID_KEY`, MAX(`TS`) AS `TS`, `KeySet`(COLLECT(ROW(`ID`, `BORGID`, `SHARTYPE`, `SHARID`, `SHARNAME`, `CREDENTIALS`, `CONTRIBUTIVEMANNER`, `CONTRIBUTIVEMONEY`, `SHAREHOLDING`, `SHARREPRESENTATIVE`, `DUTY`, `REMARK`, `BORGCODE`, `BORGNAME`, `SHARSTRUCTURE`, `SHAREHOLDINGMANNER`, `SERIALNUMBER`, `SHAREHOLDINGRATIO`, `NATURE`, `CAREA`, `BJSSJJE`, `BJSRJJE`, `BJSCZQX`, `ATTACHMENT`))) AS `sharehoiler_info`
   FROM (SELECT `BORGID` AS `OID_KEY`, `TS`, ROW(ARRAY[`ID`], ARRAY[`ID`]) AS `ID`, ROW(ARRAY[`BORGID`], ARRAY[`BORGID`]) AS `BORGID`, ROW(ARRAY[`SHARTYPE`], ARRAY[`SHARTYPE`]) AS `SHARTYPE`, ROW(ARRAY[`SHARID`], ARRAY[`SHARID`]) AS `SHARID`, ROW(ARRAY[`SHARNAME`], ARRAY[`SHARNAME`]) AS `SHARNAME`, ROW(ARRAY[`CREDENTIALS`], ARRAY[`CREDENTIALS`]) AS `CREDENTIALS`, ROW(ARRAY[`CONTRIBUTIVEMANNER`], ARRAY[`CONTRIBUTIVEMANNER`]) AS `CONTRIBUTIVEMANNER`, ROW(ARRAY[`CONTRIBUTIVEMONEY`], ARRAY[`CONTRIBUTIVEMONEY`]) AS `CONTRIBUTIVEMONEY`, ROW(ARRAY[`SHAREHOLDING`], ARRAY[`SHAREHOLDING`]) AS `SHAREHOLDING`, ROW(ARRAY[`SHARREPRESENTATIVE`], ARRAY[`SHARREPRESENTATIVE`]) AS `SHARREPRESENTATIVE`, ROW(ARRAY[`DUTY`], ARRAY[`DUTY`]) AS `DUTY`, ROW(ARRAY[`REMARK`], ARRAY[`REMARK`]) AS `REMARK`, ROW(ARRAY[`BORGCODE`], ARRAY[`BORGCODE`]) AS `BORGCODE`, ROW(ARRAY[`BORGNAME`], ARRAY[`BORGNAME`]) AS `BORGNAME`, ROW(ARRAY[`SHARSTRUCTURE`], ARRAY[`SHARSTRUCTURE`]) AS `SHARSTRUCTURE`, ROW(ARRAY[`SHAREHOLDINGMANNER`], ARRAY[`SHAREHOLDINGMANNER`]) AS `SHAREHOLDINGMANNER`, ROW(ARRAY[`SERIALNUMBER`], ARRAY[`SERIALNUMBER`]) AS `SERIALNUMBER`, ROW(ARRAY[`SHAREHOLDINGRATIO`], ARRAY[`SHAREHOLDINGRATIO`]) AS `SHAREHOLDINGRATIO`, ROW(ARRAY[`NATURE`], ARRAY[`NATURE`]) AS `NATURE`, ROW(ARRAY[`CAREA`], ARRAY[`CAREA`]) AS `CAREA`, ROW(ARRAY[`BJSSJJE`], ARRAY[`BJSSJJE`]) AS `BJSSJJE`, ROW(ARRAY[`BJSRJJE`], ARRAY[`BJSRJJE`]) AS `BJSRJJE`, ROW(ARRAY[`BJSCZQX`], ARRAY[`BJSCZQX`]) AS `BJSCZQX`, `ATTACHMENT`
         FROM (SELECT *
               FROM `BORG_JGXX_SHAREHOLDER`
               WHERE `BORGID` IS NOT NULL) AS `BORG_JGXX_SHAREHOLDER`
                  LEFT JOIN (SELECT `BIZID`, `ATTACHMENT`
                             FROM `V1202_HR_SOURCE_PART_ATTACH`
                             WHERE `TABLE_NAME` = 'borg_jgxx_shareholder') AS `ATTACH` ON `BORG_JGXX_SHAREHOLDER`.`ID` = `ATTACH`.`BIZID`)
   GROUP BY `OID_KEY`;


